"""empty message

Revision ID: 23156d03c002
Revises: e7f2f8413546
Create Date: 2022-04-10 13:05:32.421445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23156d03c002'
down_revision = 'e7f2f8413546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brewery_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('brewery', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brewery_posts')
    # ### end Alembic commands ###
