"""empty message

Revision ID: 5433d1514ea1
Revises: 21105c88eeb5
Create Date: 2022-04-11 15:11:04.420595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5433d1514ea1'
down_revision = '21105c88eeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewery_posts', sa.Column('beer', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brewery_posts', 'beer')
    # ### end Alembic commands ###
