"""empty message

Revision ID: 832021fc72b8
Revises: 
Create Date: 2022-04-10 18:12:39.238431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832021fc72b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewery_posts', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('brewery_posts', 'brewery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewery_posts', sa.Column('brewery', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('brewery_posts', 'title')
    # ### end Alembic commands ###
